id: P004132
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:55:16.078645
source_metadata:
  id: bdr:W8LS20649
  title: ཀྲུང་གོའི་ཕུགས་འདུན། བདག་གི་ཕུགས་འདུན།
  author: ''
  volumes:
    3d2b67326022486699412766530b69d8:
      image_group_id: I8LS20651
      title: ''
      volume_number: 1
      total_pages: 301
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
