id: I86858E15
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T17:39:29+00:00'
last_modified: '2022-06-07T20:28:32.510735+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20649
  title: ཀྲུང་གོའི་ཕུགས་འདུན། བདག་གི་ཕུགས་འདུན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    4D47:
      image_group_id: I8LS20651
      title: ''
      total_pages: 301
      order: 1
      base_file: 4D47.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
